# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fredyxd25
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda

custom:
  tableName: ProyectosTareas

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}/index/GSI1

package:
  include:
    - node_modules/aws-sdk/**

functions: #Funciones de Lambda
  postTask:
    handler: src/postTask.postTask
    events:
      - httpApi:
          path: /task
          method: post
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /task
          method: get
  getTasksProject:
    handler: src/getTasksProject.getTasksProject
    events:
      - httpApi:
          path: /task/{proyectoId}
          method: get
  getTasksUser:
    handler: src/getTasksUser.getTasksUser
    events:
      - httpApi:
          path: /task/user/{userId}/status/{status}
          method: get
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /task/{proyectoId}
          method: delete
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{proyectoId}
          method: put

resources: # Configuracion para DynamoDB
  Resources:
    ProjectSystemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST  # Sin preocuparte por capacidad
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL