# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fredyxd25
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:us-east-1:158735973681:table/TablaPrueba

package:
  include:
    - node_modules/aws-sdk/**

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createTask:
    handler: src/crearTarea.crearTarea
    events:
      - httpApi:
          path: /enviar
          method: post
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /visualizar
          method: get

resources: # Configuracion for dynamodb
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaPrueba
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH